### ISSUE TITLE
[question] porting process

### ISSUE THREAD

**Issue by endel** [cuongdd2/RobotlegsJS-SignalMediator#1]
Hi @cuongdd2,

Did you used [as3-to-ts](https://github.com/goodgameStudios/as3-to-ts) to help porting the extension? Or did you ported it manually?

Nice project, congrats!
Cheers!

**Comment by cuongdd2** [comment]
Hi @endel 
I ported it manually due to bug in Dictionary to Map conversion and I am too lazy to send PR to [as3-to-ts](https://github.com/goodgameStudios/as3-to-ts) :D.

Thanks for asking.
