### ISSUE TITLE
Change RobotlegsJS dependencies to new packages

### ISSUE THREAD

**Issue by pasviegas** [cuongdd2/RobotlegsJS-SignalMediator#3]
Hi! RobotlegsJS just changed the dependencies in npm to @robotlegsjs/core, @robotlegsjs/pixi and @robotlegsjs/signals. 

Would you mind updating the project accordingly, I certainly can make a pull request if need, but I would be glad if you could deploy to npm after.

Thanks!

**Comment by cuongdd2** [comment]
Please make a pull request, I'll merge and deploy to npm later. Thanks.

**Comment by pasviegas** [comment]
Thanks! Done!

**Comment by cuongdd2** [comment]
Sorry @pasviegas, this repo now is moved to RobotlegsJS organization: https://github.com/RobotlegsJS/RobotlegsJS-Pixi-SignalMediator
They'll soon publish it to npm as version 0.0.1. Please wait until then.

**Comment by pasviegas** [comment]
Cool, no problem! thanks! ;)
